server:
  port: 8080
  servlet:
    context-path: /ycej

spring:
  datasource:
    url: jdbc:mysql://118.89.199.103:3306/ycej?useSSL=false&characterEncoding=utf-8
    username: cn
    password: cheng521
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    cn:
      goldlone:
        mapper: DEBUG